#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_CARGO "/Киборги карго"
#define RND_CATEGORY_MECHFAB_SYNTH "/Синты"
#define RND_SUBCATEGORY_MECHFAB_SYNTH_PARTS "/Части Синта"

#define RND_CATEGORY_NRI_FOOD "Провизия"
#define RND_CATEGORY_NRI_MEDICAL "Медицина"
#define RND_CATEGORY_NRI_CLOTHING "Одежда"
